version: '3'
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
  mongo:
    image: mongo
  node:
    # Use dev.Dockerfile and build that image
    build:
      context: .
      dockerfile: dev.Dockerfile
    # Port mapping: localMachinePort: containerPort
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - /app/node_modules
      - .:/app
